### PR TITLE
Migrated APAddressBook 0.2.1 & swift compatibility

### PR DESCRIPTION
**Pull request by jessearmand**
- Fixed compatibility with the latest APAddressBook
- Fixed nullability type specifiers
  Migrated APAddressBook and other fixes related to how it's being used as a framework

### CODE REVIEW

**Comment by zhxnlai** [comment]
@jessearmand Thanks for the PRs! I have added you as a collaborator. Would you like to help maintain this repository?

**Comment by jessearmand** [comment]
Hi @zhxnlai

Alright sure, 
If you have some kind of suggestions on how the project should be, just let me know. 

A few essential things to add, in my mind:
- Continuous Integration
- Changelog
- Tests
- Carthage support

Thanks

**Comment by jessearmand** [comment]
@zhxnlai additionally, could you add me to the list of Pod owners? I need to add this specific pull-request as the next version.

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

`pod trunk add-owner ZLPeoplePickerViewController jesse@jessearmand.com`

**Comment by zhxnlai** [comment]
Done!

**Pull request merged**
